# Generated by Django 5.1.7 on 2026-08-08 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='الصورة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سلة',
                'verbose_name_plural': 'السلات',
            },
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الدراجة')),
                ('brand', models.CharField(choices=[('honda', 'هوندا'), ('yamaha', 'ياماها'), ('kawasaki', 'كاواساكي'), ('ducati', 'دوكاتي'), ('bmw', 'بي إم دبليو'), ('harley', 'هارلي ديفيدسون'), ('suzuki', 'سوزوكي'), ('ktm', 'كاي تي إم'), ('triumph', 'ترايمف'), ('aprilia', 'أبريليا')], max_length=50, verbose_name='العلامة التجارية')),
                ('model_year', models.PositiveIntegerField(verbose_name='سنة الصنع')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر القديم')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('short_description', models.TextField(blank=True, verbose_name='وصف مختصر')),
                ('image', models.ImageField(upload_to='motorcycles/', verbose_name='الصورة الرئيسية')),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='المخزون')),
                ('engine_cc', models.PositiveIntegerField(verbose_name='سعة المحرك (CC)')),
                ('horsepower', models.PositiveIntegerField(blank=True, null=True, verbose_name='القوة الحصانية')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='الوزن (كجم)')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='اللون')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('is_new', models.BooleanField(default=False, verbose_name='جديد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motorcycles', to='shop.category', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'دراجة نارية',
                'verbose_name_plural': 'الدراجات النارية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MotorcycleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='motorcycles/gallery/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='الوصف')),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.motorcycle', verbose_name='الدراجة')),
            ],
            options={
                'verbose_name': 'صورة إضافية',
                'verbose_name_plural': 'الصور الإضافية',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'قيد المعالجة'), ('shipped', 'تم الشحن'), ('delivered', 'تم التوصيل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المجموع')),
                ('shipping_address', models.TextField(verbose_name='عنوان الشحن')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر عند الشراء')),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.motorcycle', verbose_name='الدراجة')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'عنصر الطلب',
                'verbose_name_plural': 'عناصر الطلب',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.cart', verbose_name='السلة')),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.motorcycle', verbose_name='الدراجة')),
            ],
            options={
                'verbose_name': 'عنصر السلة',
                'verbose_name_plural': 'عناصر السلة',
                'unique_together': {('cart', 'motorcycle')},
            },
        ),
    ]
